### ISSUE TITLE
Have a way to skip the intro

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/covilla#10]
Makes the dev cycle brutal lol

**Comment by kennethshawfriedman** [comment]
I will take this one.

There should be no overlay, it should just type out the intro directly above the map, so you don't need to wait for it to finish. 

On it.

**Comment by kennethshawfriedman** [comment]
Available here: https://github.com/dvargas92495/covilla/pull/13

**Comment by dvargas92495** [comment]
If in your commit message you just write "(Closes #10)" it will autolink, instead of having to make another comment

**Comment by kennethshawfriedman** [comment]
Good to know!

Complete.
